name: 00 - Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
      TF_VAR_github_actions_sp_object_id: ${{ secrets.AZURE_SP_OBJECT_ID }}
      TF_VAR_resource_group_name: ${{ vars.TF_RESOURCE_GROUP_NAME }}
      TF_VAR_acr_name: ${{ vars.TF_ACR_NAME }}
      TF_VAR_storage_account_name: ${{ vars.TF_STORAGE_ACCOUNT_NAME }}
      TF_VAR_aks_cluster_name: ${{ vars.TF_AKS_CLUSTER_NAME }}
      TF_VAR_aks_dns_prefix: ${{ vars.TF_AKS_DNS_PREFIX }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan